data_store: 'mysql'  # 'sqlite' or 'mysql'
data_source: 'gspro' # 'gspro' or 'mlm2gspro'
log_level: INFO

# for api binding
port: 9210
listen_address: '0.0.0.0'

# for gspro mode (use mysql)
gspro:
  log_file_path: 'C:\\Users\\almiller\\AppData\\LocalLow\\GSPro\\GSPro\\output_log.txt'
mysql:
  host: 'x.x.x.x'
  db: 'swingstudio'
  table: 'shots'
  user: 'xxxx'
  pass: 'xxxx'

# for mls2pro-gspro-connector mode (use sqlite)
log_file_path: 'E:\\MLM-2PRO-GSPro-Connector_V1.04.09\\appdata\\logs\\mlm2pro-gspro-connect.log'
database_path: 'sqlite://E:\\swing-logger\\swing.db'
json_fields:
  - new_shot
  - club
  - speed
  - spin_axis
  - total_spin
  - hla
  - vla
  - club_speed
  - back_spin
  - side_spin
  - path
  - face_to_target
  - angle_of_attack
  - speed_at_impact
monitored_log_entries:
  - "GSProConnect: Success"
