name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: Silleellie/pylint-github-action@v2.1
      with:
        lint-path: src  # lint src package
        python-version: 3.12  # python version which will lint the package
        color-bad-score: red
        color-ok-score: orange
        color-good-score: yellow
        color-perfect-score: brightgreen